### ISSUE TITLE
pycurl.error: (35, 'Unknown SSL protocol error)

### ISSUE THREAD

**Issue by xieexiaotuzi** [siznax/wptools#143]
Hi, when I run 
"infobox = wptools.page('Nexus Q').get_parse().data['infobox']"

I always get the error 
"pycurl.error: (35, 'Unknown SSL protocol error in connection to en.wikipedia.org:443 ')"

In detail,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python2.7/site-packages/wptools/page.py", line 521, in get
    self.get_query(False, proxy, timeout)
  File "//anaconda/lib/python2.7/site-packages/wptools/page.py", line 638, in get_query
    self._get('query', show, proxy, timeout)
  File "//anaconda/lib/python2.7/site-packages/wptools/core.py", line 175, in _get
    response = req.get(qstr, qobj.status)
  File "//anaconda/lib/python2.7/site-packages/wptools/request.py", line 76, in get
    return self.curl_perform(crl)
  File "//anaconda/lib/python2.7/site-packages/wptools/request.py", line 84, in curl_perform
    crl.perform()
pycurl.error: (35, 'Unknown SSL protocol error in connection to en.wikipedia.org:443 ')

My wptools version is 0.4.17 and on Mac. Could anyone help me thanks a lot.

**Comment by xieexiaotuzi** [comment]
@siznax

**Comment by siznax** [comment]
Thanks for trying wptools, @xieexiaotuzi! This is a fairly common problem with pycurl on some systems. Please see https://github.com/siznax/wptools/issues/68 and let me know if you still have trouble.

**Comment by siznax** [comment]
Hi @xieexiaotuzi. Thanks again for trying wptools. I deleted my previous comment because I misunderstood the problem. It's working for me, so I think you may be blocked from accessing `en.wikipedia.org` for some reason.

**Comment by siznax** [comment]
Please look into these tools: `curl` and `openssl`. For example, on my system:

```
$ openssl version -a
LibreSSL 2.6.5
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx)
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"
```

You may learn something from this command too:

```
$ curl -I https://en.wikipedia.org/wiki/Nexus_Q
```

You can use https://brew.sh/ to install these packages on Mac OS.

**Comment by lisongx** [comment]
@siznax 
Could be accessing issue,  make sense to try using curl or wget to fetch a page to see.

I know some territory think Wikipedia is blocked (like China and Iran)

**Comment by JianyuZhao7** [comment]
@lisongx Thanks for your answer. I try to access from U.S. using vpn and failed too. So any ideas? Thanks.

**Comment by lisongx** [comment]
@JianyuZhao7 
Do you have the same issue as @xieexiaotuzi ?
what if you try use curl to request the en wikipedia?
 `curl -I https://en.wikipedia.org/wiki/Nexus_Q`

**Comment by asifkhan69** [comment]
if you are using Mac with High Serria try this:
uninstall your wptools and pycurl and than do this to install pycrul
pip uninstall pycurl
export PYCURL_SSL_LIBRARY=openssl
export LDFLAGS=-L/usr/local/opt/openssl/lib;export CPPFLAGS=-I/usr/local/opt/openssl/include;pip install pycurl --compile --no-cache-dir

install wptools again than see still you are getting this error.

**Comment by siznax** [comment]
@naspuka @asifkhan69 this issue is about a pycurl _error_, not about pycurl _installation_.

Please see #68 to resolve pycurl setup issues, usually related to SSL library paths.

**Comment by shouhulantian** [comment]
I am in China and I met the same problem. Wikipedia is blocked in China so I used VPN. At first, I wrote  `fela = wptools.page('Fela Kuti').get_parse(proxy='http://127.0.0.1:1080')` but the same error appeared. After careful examination, I found `self._set_data(action)` in core.py caused this problem. This function does not pass "proxy" to afterward function but later `self._get('imageinfo', show, proxy, timeout)` in page.py starts a new curl with the proxy initialized to be None. Finally, 443 appeared.  So I wrote `crl.setopt(pycurl.PROXY,'http://127.0.0.1:1080')` in func curl_setup and this problem was fixed.
