### ISSUE TITLE
Support more wikis by allowing insecure requests

### ISSUE THREAD

**Issue by siznax** [siznax/wptools#19]
Currently, all queries use HTTPS, so if you try a non-Wikimedia site, you may get an SSL error:

```
>>> p = wptools.page(wiki='tolkiengateway.net')
tolkiengateway.net (action=random) None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wptools/core.py", line 113, in __init__
    self.get_random()
  File "wptools/core.py", line 588, in get_random
    response = self.__fetch.curl(query)
  File "wptools/fetch.py", line 110, in curl
    return self.curl_perform(crl)
  File "wptools/fetch.py", line 118, in curl_perform
    crl.perform()
pycurl.error: (7, 'Failed to connect to tolkiengateway.net port 443: Connection refused')
```

If we adjust the query to use 'http' instead of 'https':

```
diff --git a/wptools/fetch.py b/wptools/fetch.py
index 249b210..81250d7 100644
--- a/wptools/fetch.py
+++ b/wptools/fetch.py
@@ -176,7 +176,7 @@ class WPToolsFetch(object):

         self.action = action
         self.thing = thing
-        return qry
+        return qry.replace('https', 'http')
```

Then we can access more MediaWiki instances...

```
>>> p = wptools.page(wiki='tolkiengateway.net')
tolkiengateway.net (action=random) None
Helm's_Deep_(scene) (en)
{
  lang: en
  pageid: 41211
  title: Helm's_Deep_(scene)
}
```

**Comment by siznax** [comment]
Fixed with 878d2341322fa99501c3dae31ae0e768575f8170 "Support for non-https wikis"
