### ISSUE TITLE
wikibase lookup bug

### ISSUE THREAD

**Issue by seansay** [siznax/wptools#24]
For example `q = wptools.page(wikibase='Q43303').get_query` will always give back a None page?

I think in this case, the code will throw a exception if it don't have enough information to get the query information.

**Comment by siznax** [comment]
Right. With `wikibase` only, you would need to use `get_wikidata()` first. The `get` method will do the right thing:

```python
>>> q = wptools.page(wikibase='Q43303').get()
Q43303 (en)
{
  images: <dict(1)> {wimage}
  lang: en
  wikibase: Q43303
}
en.wikipedia.org (action=wikidata) Q43303
en.wikipedia.org (action=wikidata) Q30|Q5|Q7010775
en.wikipedia.org (action=query) Malcolm_X
en.wikipedia.org (action=parse) 20796
Malcolm_X (en) {
 ...
}
```

**Comment by seansay** [comment]
apologied if I'm having too much problems here!



running this code I get this traceback
```
 p = wptools.page(wikibase='Q2274', silent=True, lang='zh').get()
```

```
  File "/var/dae/prelease/20161020_seanlee_fm_EoHQGQ/fm/venv/src/wptools/wptools/core.py", line 488, in get
    self.get_wikidata(show=False)
  File "/var/dae/prelease/20161020_seanlee_fm_EoHQGQ/fm/venv/src/wptools/wptools/core.py", line 682, in get_wikidata
    self._set_wikidata()
  File "/var/dae/prelease/20161020_seanlee_fm_EoHQGQ/fm/venv/src/wptools/wptools/core.py", line 478, in _set_wikidata
    self.title = self.label.replace(' ', '_')
AttributeError: 'NoneType' object has no attribute 'replace'

```

**Comment by siznax** [comment]
Haha, no problem! Finding bugs is very helpful. I need more test coverage here. I pushed the fix: e1761f740762a568218c9bf709fa8ed7a5fbc439 

In this example, you'll probably want to use `lang='zh-cn'`:

```python
>>> p = wptools.page(wikibase='Q2274', lang='zh-cn').get_wikidata()
Q2274 (zh-cn)
{
  images: <dict(1)> {wimage}
  lang: zh-cn
  wikibase: Q2274
}
zh-cn.wikipedia.org (action=wikidata) Q2274
zh-cn.wikipedia.org (action=wikidata) Q8341|Q30|Q5|Q24068510
查特·贝克 (zh-cn)
{
  claims: <dict(4)> {Q24068510, Q30, Q5, Q8341}
  g_claims: <dict(3)> {info, query, response}
  g_wikidata: <dict(3)> {info, query, response}
  image: https://upload.wikimedia.org/wikipedia/commons/6/6d/Chet675.jpg
  images: <dict(1)> {wimage}
  label: 查特·贝克
  lang: zh-cn
  props: <dict(8)> {P136, P18, P27, P31, P345, P569, P570, P910}
  title: 查特·贝克
  wikibase: https://www.wikidata.org/wiki/Q2274
  wikidata: <dict(7)> {IMDB, birth, citizenship, death, genre, image...
}
```

**Comment by seansay** [comment]
@siznax 
Thanks, so when should I use `zh-cn` and `zh`? 

seems that for wikidata  `>>> wptools.page(wikibase='Q2274', lang='zh-cn').get_wikidata()` you can us `zh-cn`, but for others, you will need to use `zh`? 

``
zh-cn.wikipedia.org (action=query) None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/dae/prelease/20161020_seanlee_fm_EoHQGQ/fm/venv/src/wptools/wptools/core.py", line 583, in get_query
    query['response'] = self.__fetch.curl(qry)
  File "/var/dae/prelease/20161020_seanlee_fm_EoHQGQ/fm/venv/src/wptools/wptools/fetch.py", line 113, in curl
    return self.curl_perform(crl)
  File "/var/dae/prelease/20161020_seanlee_fm_EoHQGQ/fm/venv/src/wptools/wptools/fetch.py", line 121, in curl_perform
    crl.perform()
pycurl.error: (6, "Couldn't resolve host 'zh-cn.wikipedia.org'")
>>> wptools.page(wikibase='Q2274', lang='zh-cn').get_query()
```

**Comment by siznax** [comment]
Hi @seansay. You'll need to select the language choice that is appropriate for each API (MediaWiki, Wikidata, or RESTBase). In most cases, the language codes/subdomains are the same for every API. 

Not so for Chinese—as you know there are [many variants](https://en.wikipedia.org/wiki/Chinese_Wikipedia), `zh`, `zh-cn`, `zh-classical`, `wuu`, `zh-yue`, etc. And in this case (Chet Baker) there are _no_ Chinese variants of the English Wikipedia article available—unbelievable! But hey, it's Wikipedia, anyone can edit it! So please add 查特·贝克 to the Wikipedia of your choice.

If a Chinese article existed for your target on a Mediawiki instance, then you would use the language code for that particular subdomain—probably 'zh' or 'zh-cn':

```python
>>> p = wptools.page(wikibase='Q2274', lang='zh-cn').get_wikidata()
...
>>> p.lang = 'zh'
>>> p.get_query()
>>> p.get_parse()
...
```

That would give you a mix of `zh-cn` data from _Wikidata_ and `zh` info from _MediaWiki_.

You can also try the `wiki` parameter with `get`:

```python
>>> p = wptools.page('中文维基百科', wiki='zh.wikipedia.org').get()
zh.wikipedia.org (action=query) 中文维基百科
zh.wikipedia.org (action=parse) 623
zh.wikipedia.org (action=wikidata) Q30239
zh.wikipedia.org (action=wikidata) Q10876391
中文维基百科 (en)
{
  description: Wikipedia in Chinese
  ...
}
```

Does that make sense?

**Comment by siznax** [comment]
Also, as you noted elsewhere, the Chinese Wikipedia offers different "flavors" of Chinese for many pages, for example:

* https://zh.wikipedia.org/zh-cn/Wikipedia:%E9%A6%96%E9%A1%B5
* https://zh.wikipedia.org/zh-hk/Wikipedia:%E9%A6%96%E9%A1%B5
* https://zh.wikipedia.org/zh-mo/Wikipedia:%E9%A6%96%E9%A1%B5
* https://zh.wikipedia.org/zh-sg/Wikipedia:%E9%A6%96%E9%A1%B5
* https://zh.wikipedia.org/zh-tw/Wikipedia:%E9%A6%96%E9%A1%B5

Let's handle that in #26

**Comment by seansay** [comment]
@siznax 
thanks for the help!

So basically for wikidata, there is a language code for `zh-cn`, but for wikipedia instance, there are only `zh`, but variants for the same `zh`?


Yes it's sad that in Chinese wikipedia , we don't have that many pages for many reasons……
