### ISSUE TITLE
get_imageinfo hangs on proxy with timeout

### ISSUE THREAD

**Issue by seansay** [siznax/wptools#49]
timeout seems not working here
```
>>> wptools.page(wikibase='Q312559', lang='zh').get(proxy=DOUBAN_PROXY, timeout=2)
Q312559 (zh)
{
  lang: zh
  wikibase: Q312559
}
www.wikidata.org (wikidata) Q312559
www.wikidata.org (claims) Q21|Q5|Q11399
zh.wikipedia.org (query) 比尔·怀曼
zh.wikipedia.org (parse) 1542057
zh.wikipedia.org (imageinfo) File:Bill Wyman 2009.jpg
```

BTW, is there a way to ignnore imageinfo processing, since I only need the text data

**Comment by siznax** [comment]
Hi @seansay! I added `CURLOPT_VERBOSE` so you can see exactly what's going on with a327173844d836a9fb5eb69150ea7b09232dd49e

Take a look at stderr after adding `verbose=True`:

```
wptools.page(wikibase='Q312559', lang='zh').get(proxy=DOUBAN_PROXY, timeout=2, verbose=True)
```

We may want to try `CURLOPT_HTTPPROXYTUNNEL` depending on the results. 

It would be best if you could test that from your location by adjusting `fetch.curl_setup`.

**Comment by siznax** [comment]
I opened #51 so you'll have support to skip selected requests.

**Comment by seansay** [comment]
@siznax 
thanks so much for this patch, the default behaviour seems doing a lot than what i'm expected.

I'll open the verbose mode to see which request blocks

**Comment by seansay** [comment]
seems that the request hang up at this, and the `timeout` parameter isn't working here?

```
<
* Curl_http_done: called premature == 0
* Connection #0 to host gfw2 left intact
  bytes: 28013.0
  content: application/json; charset=utf-8
  kB/s: 16.5
  seconds: 1.694
  status: 200
  url: https://zh.wikipedia.org/w/api.php?action=parse&contentmodel=text&disableeditsection=&disablelimitreport=&disabletoc=&prop=text|iwlinks|parsetree|wikitext|displaytitle|properties&pageid=3014841&variant=zh-cn
  user-agent: wptools/0.2.1 (https://github.com/siznax/wptools) PycURL/7.43.0 libcurl/7.50.3 OpenSSL/1.0.2h zlib/1.2.8 nghttp2/1.7.1
zh.wikipedia.org (imageinfo) File:Sam Cooke 2.jpg
*   Trying 93.46.8.89...
* TCP_NODELAY set
* connect to 93.46.8.89 port 443 failed: Connection timed out
* Failed to connect to zh.wikipedia.org port 443: Connection timed out
* Closing connection 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/dae/apps/fm/venv/src/wptools/wptools/core.py", line 625, in get
    self.get_parse(show, proxy, timeout)
  File "/var/dae/apps/fm/venv/src/wptools/wptools/core.py", line 679, in get_parse
    self._request('parse', show, proxy, timeout)
  File "/var/dae/apps/fm/venv/src/wptools/wptools/core.py", line 397, in _request
    self.get_imageinfo(show=False)
  File "/var/dae/apps/fm/venv/src/wptools/wptools/core.py", line 660, in get_imageinfo
    self._request('imageinfo', show, proxy, timeout)
  File "/var/dae/apps/fm/venv/src/wptools/wptools/core.py", line 375, in _request
    req['response'] = _fetch.curl(query)
  File "/var/dae/apps/fm/venv/src/wptools/wptools/fetch.py", line 131, in curl
    return self.curl_perform(crl)
  File "/var/dae/apps/fm/venv/src/wptools/wptools/fetch.py", line 139, in curl_perform
    crl.perform()
pycurl.error: (7, 'Failed to connect to zh.wikipedia.org port 443: Connection timed out')

```

**Comment by siznax** [comment]
@seansay, thanks for trying that out. Since it's happening during connect, let's add [CONNECTTIMEOUT](https://curl.haxx.se/libcurl/c/CURLOPT_CONNECTTIMEOUT.html) as well.  The docs are not perfectly clear:

```
CURLOPT_TIMEOUT - set maximum time the request is allowed to take 
CURLOPT_CONNECTTIMEOUT - timeout for the connect phase 
```

Let's try using the same timeout for both, and see if that is acceptable.

**Comment by seansay** [comment]
@siznax 
lgtm for this.

**Comment by seansay** [comment]
👏
