### ISSUE TITLE
ImportError installing wptools

### ISSUE THREAD

**Issue by GonzMG** [siznax/wptools#59]
Hello! When I try to install wptools by the console, this error appears:

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/home/gonzalo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/gonzalo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/gonzalo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/gonzalo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

How can I fix that? 
Thanks.

**Comment by siznax** [comment]
Thanks for your question, @GonzMG. It looks like your `pip` doesn't like one or more of your installed packages, namely `requests`, which is not required by `wptools`.

I would make sure `pip` is up to date (9.0.1), and create a fresh virtual environment for `wptools`: https://virtualenvwrapper.readthedocs.io/en/latest/

**Comment by seansay** [comment]
maybe upgrade `pip` and try again?

**Comment by siznax** [comment]
Closing, unless this problem resurfaces.
