### ISSUE TITLE
PIP install not working

### ISSUE THREAD

**Issue by lethargilistic** [siznax/wptools#65]
I see you just updated last month, and you should know that it's currently not possible to install via pip, using Python 3. When this happens to me, something usually went wrong with creating the wheel or I forgot to upload it.

Here's the error:

```zsh
(venv) json (master) » pip install wptools                                 ~/dev/dcapi/dcapi/data/json  
Collecting wptools
  Downloading wptools-0.2.3-py2.py3-none-any.whl
Collecting pycurl (from wptools)
  Downloading pycurl-7.43.0.tar.gz (182kB)
    100% |████████████████████████████████| 184kB 2.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-h457tqte/pycurl/setup.py", line 103, in configure_unix
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-h457tqte/pycurl/setup.py", line 823, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-build-h457tqte/pycurl/setup.py", line 497, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-build-h457tqte/pycurl/setup.py", line 71, in __init__
        self.configure()
      File "/tmp/pip-build-h457tqte/pycurl/setup.py", line 107, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-h457tqte/pycurl/

```

**Comment by siznax** [comment]
Thanks for opening an issue, @lethargilistic. The wheel has been [in place](https://pypi.python.org/pypi/wptools/#downloads) since 2017-04-18, and the Travis build [succeeded](https://travis-ci.org/siznax/wptools/builds/224575495) for Python 3.5. 

Any other suggestions?

**Comment by siznax** [comment]
Also...


```
steve@hypatia ~
$ python3 -m venv /Users/steve/.virtualenvs/fresh35

steve@hypatia ~
$ source /Users/steve/.virtualenvs/fresh35/bin/activate

[fresh35] steve@hypatia ~
$ pip --version
pip 9.0.1 from /Users/steve/.virtualenvs/fresh35/lib/python3.5/site-packages (python 3.5)

[fresh35] steve@hypatia ~
$ pip install --no-cache-dir wptools
Requirement already satisfied: wptools in ./Code/wptools
Collecting certifi (from wptools)
  Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB)
    100% |████████████████████████████████| 378kB 487kB/s
Collecting html2text (from wptools)
  Downloading html2text-2016.9.19.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 766kB/s
Collecting lxml (from wptools)
  Downloading lxml-3.7.3.tar.gz (3.8MB)
    100% |████████████████████████████████| 3.8MB 529kB/s
Collecting pycurl (from wptools)
  Downloading pycurl-7.43.0.tar.gz (182kB)
    100% |████████████████████████████████| 184kB 604kB/s
Installing collected packages: certifi, html2text, lxml, pycurl
  Running setup.py install for html2text ... done
  Running setup.py install for lxml ... done
  Running setup.py install for pycurl ... done
Successfully installed certifi-2017.4.17 html2text-2016.9.19 lxml-3.7.3 pycurl-7.43.0

[fresh35] steve@hypatia ~
$ python
Python 3.5.2 (default, Jun 29 2016, 13:43:58)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wptools
>>> p = wptools.page()
en.wikipedia.org (random) 🍜
MV_C.T.M.A._Voyageur (en)
{
  actions: <list(6)>
  lang: en
  pageid: 41577082
  title: MV_C.T.M.A._Voyageur
}
>>>
```

**Comment by siznax** [comment]
@lethargilistic you may need to update your system to use pycurl.

**Comment by lethargilistic** [comment]
It was on my end. Extremely strange. I've never had an issue like that before. Ah well, live and learn.

**Comment by babaakki25** [comment]
Hello, I am facing a similar issue in Python3.5.2. I have tried everything mentioned above.

**Comment by LukeTonin** [comment]
I encountered a similar issue and the problem was pycurl was not installed and it's installation was failing due to missing libraries. I ran:
```
sudo apt install libcurl4-openssl-dev libssl-dev 
```
After that I could install wptools without a problem.
